#pragma checksum "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9F4412CD1F7240020A9118CED1E54883786C6A87"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jmann {
    
    
    public partial class sys_ReportServer : System.Web.SessionState.IRequiresSessionState {
        
        
        #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        #line default
        #line hidden
        
        
        #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
        protected global::Microsoft.Reporting.WebForms.ReportViewer rptViewer;
        
        #line default
        #line hidden
        
        
        #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        #line default
        #line hidden
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
    }
}
namespace ASP {
    
    #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
    using Microsoft.Reporting.WebForms;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class sys_reportserver_aspx : global::jmann.sys_ReportServer, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sys_reportserver_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/sys_ReportServer.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.sys_reportserver_aspx.@__initialized == false)) {
                global::ASP.sys_reportserver_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/sys_ReportServer.aspx";
                dependencies[1] = "~/sys_ReportServer.aspx.cs";
                global::ASP.sys_reportserver_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.sys_reportserver_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 9 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 9 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Reports"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 10 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 10 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Href = "~/Styles/Site.css";
            
            #line default
            #line hidden
            
            #line 10 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 10 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 11 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 11 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Href = "~/Styles/global.css";
            
            #line default
            #line hidden
            
            #line 11 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 11 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!--    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl2;
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("  -->\r\n  "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 8 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptReference @__BuildControl__control7() {
            global::System.Web.UI.ScriptReference @__ctrl;
            
            #line 17 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::System.Web.UI.ScriptReference();
            
            #line default
            #line hidden
            
            #line 17 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Path = "Scripts/jquery-1.4.1.min.js";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control6(System.Web.UI.ScriptReferenceCollection @__ctrl) {
            global::System.Web.UI.ScriptReference @__ctrl1;
            
            #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptManager @__BuildControlScriptManager1() {
            global::System.Web.UI.ScriptManager @__ctrl;
            
            #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::System.Web.UI.ScriptManager();
            
            #line default
            #line hidden
            this.ScriptManager1 = @__ctrl;
            
            #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.ID = "ScriptManager1";
            
            #line default
            #line hidden
            
            #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.EnablePageMethods = true;
            
            #line default
            #line hidden
            
            #line 15 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            this.@__BuildControl__control6(@__ctrl.Scripts);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.Reporting.WebForms.ReportViewer @__BuildControlrptViewer() {
            global::Microsoft.Reporting.WebForms.ReportViewer @__ctrl;
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::Microsoft.Reporting.WebForms.ReportViewer();
            
            #line default
            #line hidden
            this.rptViewer = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.ID = "rptViewer";
            
            #line default
            #line hidden
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Font.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Font.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(8D, global::System.Web.UI.WebControls.UnitType.Point));
            
            #line default
            #line hidden
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.ProcessingMode = global::Microsoft.Reporting.WebForms.ProcessingMode.Remote;
            
            #line default
            #line hidden
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.WaitMessageFont.Names = new string[] {
                    "Verdana"};
            
            #line default
            #line hidden
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.WaitMessageFont.Size = new System.Web.UI.WebControls.FontUnit(new System.Web.UI.WebControls.Unit(14D, global::System.Web.UI.WebControls.UnitType.Point));
            
            #line default
            #line hidden
            
            #line 21 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.SizeToReportContent = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlForm1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.Form1 = @__ctrl;
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.ID = "Form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptManager @__ctrl1;
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl1 = this.@__BuildControlScriptManager1();
            
            #line default
            #line hidden
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <div>\r\n            "));
            
            #line default
            #line hidden
            global::Microsoft.Reporting.WebForms.ReportViewer @__ctrl2;
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl2 = this.@__BuildControlrptViewer();
            
            #line default
            #line hidden
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 14 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        </div>\r\n   "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(sys_reportserver_aspx @__ctrl) {
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Title = "Reports";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl.Theme = "Theme1";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
                        ".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n\r\n<html xmlns=\"http://www.w3.org/1" +
                        "999/xhtml\">\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<body>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__ctrl2 = this.@__BuildControlForm1();
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</body>\r\n</html>"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\JMann\Finance\Application\Finance\sys_ReportServer.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.sys_reportserver_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.sys_reportserver_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -312876748;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
