#pragma checksum "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9590FC16AD058BEAE483EEED20FF1A5738EA358B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jmann {
    
    
    public partial class ThriftOS_Update : System.Web.SessionState.IRequiresSessionState {
        
        
        #line 14 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.Label LblTitle;
        
        #line default
        #line hidden
        
        
        #line 22 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        
        #line default
        #line hidden
        
        
        #line 27 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDate;
        
        #line default
        #line hidden
        
        
        #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvDate;
        
        #line default
        #line hidden
        
        
        #line 32 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.Label gridMessage1;
        
        #line default
        #line hidden
        
        
        #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        #line default
        #line hidden
        
        
        #line 49 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.Label gridMessage2;
        
        #line default
        #line hidden
        
        
        #line 54 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        
        #line default
        #line hidden
        
        
        #line 59 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.Label lblNoLocationOrDate;
        
        #line default
        #line hidden
        
        
        #line 64 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.Label lblDone;
        
        #line default
        #line hidden
        
        
        #line 69 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.Label lblError;
        
        #line default
        #line hidden
        
        
        #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
        protected global::System.Web.UI.WebControls.SqlDataSource dsEmployeeIssues;
        
        #line default
        #line hidden
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
    }
}
namespace ASP {
    
    #line 3 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class thriftos_update_aspx : global::jmann.ThriftOS_Update, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public thriftos_update_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/ThriftOS_Update.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.thriftos_update_aspx.@__initialized == false)) {
                global::ASP.thriftos_update_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[6];
                dependencies[0] = "~/ThriftOS_Update.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/UC/footer.ascx";
                dependencies[4] = "~/UC/footer.ascx.cs";
                dependencies[5] = "~/ThriftOS_Update.aspx.cs";
                global::ASP.thriftos_update_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.thriftos_update_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(22628, 318, true));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLblTitle() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 14 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.LblTitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 14 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "LblTitle";
            
            #line default
            #line hidden
            
            #line 14 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Text = "Update Daily Register and ZTape from ThriftOS";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlLocation() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 22 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.ddlLocation = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 22 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "ddlLocation";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 27 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "TextBoxDate";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 27 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "TxtDate";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvDate() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvDate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "CompvDate";
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ControlToValidate = "TxtDate";
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ErrorMessage = "Invalid date!";
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Date;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlgridMessage1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 32 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.gridMessage1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 32 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "gridMessage1";
            
            #line default
            #line hidden
            
            #line 32 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Text = "The following employees in ThriftOS do not have employee records in SMS Finance t" +
                "hat have matching Employee ID, Last Name, and First Name:";
            
            #line default
            #line hidden
            
            #line 32 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control3() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 40 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.DataField = "EMPLOYEE_ID";
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.HeaderText = "Employee ID";
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.SortExpression = "EMPLOYEE_ID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control4() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 41 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.DataField = "LAST_NAME";
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.HeaderText = "Last Name";
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.SortExpression = "LAST_NAME";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control5() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 42 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 42 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.DataField = "FIRST_NAME";
            
            #line default
            #line hidden
            
            #line 42 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.HeaderText = "First Name";
            
            #line default
            #line hidden
            
            #line 42 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 42 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.SortExpression = "FIRST_NAME";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGridView1() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.GridView1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "GridViewCloverField";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "GridView1";
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "EMPLOYEE_ID"};
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.DataSourceID = "dsEmployeeIssues";
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            this.@__BuildControl__control2(@__ctrl.Columns);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlgridMessage2() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 49 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.gridMessage2 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 49 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "gridMessage2";
            
            #line default
            #line hidden
            
            #line 49 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Text = "Please enter or update the SMS Finance employee records and try again.";
            
            #line default
            #line hidden
            
            #line 49 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnUpdate() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 54 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnUpdate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 54 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "btnUpdate";
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Text = "Update";
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnUpdate_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblNoLocationOrDate() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 59 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblNoLocationOrDate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 59 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "lblNoLocationOrDate";
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Text = "Please select a Location and a Date";
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblDone() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 64 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblDone = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 64 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "lblDone";
            
            #line default
            #line hidden
            
            #line 64 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Text = "DONE!";
            
            #line default
            #line hidden
            
            #line 64 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 69 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblError = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 69 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "lblError";
            
            #line default
            #line hidden
            
            #line 69 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control7() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 81 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 81 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Name = "locationID";
            
            #line default
            #line hidden
            
            #line 81 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.DefaultValue = "0";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control8() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 82 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 82 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Name = "date";
            
            #line default
            #line hidden
            
            #line 82 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.DefaultValue = "1/1/2000";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control6(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.Parameter @__ctrl1;
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Parameter @__ctrl2;
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl2 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.SqlDataSource @__BuildControldsEmployeeIssues() {
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl;
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.SqlDataSource();
            
            #line default
            #line hidden
            this.dsEmployeeIssues = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.ID = "dsEmployeeIssues";
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.SelectCommand = "spThriftOS_EmployeeCheck";
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.SelectCommandType = global::System.Web.UI.WebControls.SqlDataSourceCommandType.StoredProcedure;
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            this.@__BuildControl__control6(@__ctrl.SelectParameters);
            
            #line default
            #line hidden
            @__ctrl.ConnectionString = global::System.Convert.ToString(System.Web.Compilation.ConnectionStringsExpressionBuilder.GetConnectionString("App-MainConnectionString"), global::System.Globalization.CultureInfo.CurrentCulture);
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <h3 id=\"h3AddEditRecord\" class=\"ui-widget-header\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl1 = this.@__BuildControlLblTitle();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(22946, 266, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl2 = this.@__BuildControlddlLocation();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" \r\n                        </td>\r\n                    </tr>\r\n                    " +
                        "<tr>\r\n\t\t                <td class=\"style120B\">Date</td>\r\n                       " +
                        " <td class=\"style90B\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl3 = this.@__BuildControlTxtDate();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t                <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl4;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl4 = this.@__BuildControlCompvDate();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n                    </tr>\r\n                    <tr>\r\n \t\t                <t" +
                        "d colspan=\"2\" style=\"width: 250px;color: red\">\r\n                             "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl5;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl5 = this.@__BuildControlgridMessage1();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \t\t                </td>\r\n                    </tr>\r\n                    <tr>\r\n" +
                        "  \t\t                <td colspan=\"2\" style=\"width: 250px\">\r\n\t                    " +
                        "    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl6;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl6 = this.@__BuildControlGridView1();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
                        "tr>\r\n \t\t                <td colspan=\"2\" style=\"width: 250px;color: red\">\r\n      " +
                        "                       "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl7;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl7 = this.@__BuildControlgridMessage2();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \t\t                </td>\r\n                    </tr>\r\n                    <tr>\r\n" +
                        "                        <td colspan=\"2\" style=\"text-align: center\">\r\n           " +
                        "                 "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl8;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl8 = this.@__BuildControlbtnUpdate();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
                        "tr>\r\n \t\t                <td colspan=\"2\" style=\"color: red\">\r\n                   " +
                        "          "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl9;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl9 = this.@__BuildControllblNoLocationOrDate();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \t\t                </td>\r\n                    </tr>\r\n                    <tr>\r\n" +
                        " \t\t                <td colspan=\"2\" style=\"text-align: center;color: blue\">\r\n    " +
                        "                         "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl10;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl10 = this.@__BuildControllblDone();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \t\t                </td>\r\n                    </tr>\r\n                    <tr>\r\n" +
                        " \t\t                <td colspan=\"2\" style=\"color: red\">\r\n                        " +
                        "     "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl11;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl11 = this.@__BuildControllblError();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \t\t                </td>\r\n                    </tr>\r\n                </table>\r\n" +
                        "            </td>\r\n        </tr>\r\n    </table>\r\n      \r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl12;
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl12 = this.@__BuildControldsEmployeeIssues();
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n \r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(thriftos_update_aspx @__ctrl) {
            
            #line 1 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Title = "Employee";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__ctrl.Theme = "Theme1";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 13 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\JMann\Finance\Application\Finance\ThriftOS_Update.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.thriftos_update_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.thriftos_update_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1918645580;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
