#pragma checksum "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A563AD313A95A02187BA012CAA7D91EF0052BEE2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jmann {
    
    
    public partial class GridViewAddEdit_Location : System.Web.SessionState.IRequiresSessionState {
        
        
        #line 36 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        #line default
        #line hidden
        
        
        #line 48 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.HiddenField HfldLocationID;
        
        #line default
        #line hidden
        
        
        #line 49 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtLocationID;
        
        #line default
        #line hidden
        
        
        #line 54 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtName;
        
        #line default
        #line hidden
        
        
        #line 59 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDescription;
        
        #line default
        #line hidden
        
        
        #line 64 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtFeetOfRack;
        
        #line default
        #line hidden
        
        
        #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvFeetOfRack;
        
        #line default
        #line hidden
        
        
        #line 70 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.Button BtnAddRecord;
        
        #line default
        #line hidden
        
        
        #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.Button BtnUpdateRecord;
        
        #line default
        #line hidden
        
        
        #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        #line default
        #line hidden
        
        
        #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        #line default
        #line hidden
        
        
        #line 110 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        
        #line default
        #line hidden
        
        
        #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
        
        #line default
        #line hidden
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
    }
}
namespace ASP {
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class gridviewaddedit_location_aspx : global::jmann.GridViewAddEdit_Location, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public gridviewaddedit_location_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/GridViewAddEdit_Location.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.gridviewaddedit_location_aspx.@__initialized == false)) {
                global::ASP.gridviewaddedit_location_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[6];
                dependencies[0] = "~/GridViewAddEdit_Location.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/UC/footer.ascx";
                dependencies[4] = "~/UC/footer.ascx.cs";
                dependencies[5] = "~/GridViewAddEdit_Location.aspx.cs";
                global::ASP.gridviewaddedit_location_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.gridviewaddedit_location_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent1));
        }
        
        private void @__RenderContent1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.WriteUTF8ResourceString(@__w, 3019, 529, true);
            
            #line 17 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
     @__w.Write(TxtLocationID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").attr(\'disabled\', false);\r\n            $(\"#");
            
            #line 18 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtLocationID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 19 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 20 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtDescription.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 21 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtFeetOfRack.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n        }\r\n\r\n        function assignRetrievedItems(msg) {\r\n\t        " +
                    "$(\"#");
            
            #line 25 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
     @__w.Write(HfldLocationID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(msg.d.LocationID);\r\n\t        $(\"#");
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
     @__w.Write(TxtLocationID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").attr(\'disabled\', true);\r\n            $(\"#");
            
            #line 27 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtLocationID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.LocationID));\r\n            $(\"#");
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.Name));\r\n            $(\"#");
            
            #line 29 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtDescription.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.Description));\r\n            $(\"#");
            
            #line 30 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
        @__w.Write(TxtFeetOfRack.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.FeetOfRack));\r\n        }\r\n    </script>\r\n");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptManager @__BuildControlScriptManager1() {
            global::System.Web.UI.ScriptManager @__ctrl;
            
            #line 36 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.ScriptManager();
            
            #line default
            #line hidden
            this.ScriptManager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 36 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "ScriptManager1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHfldLocationID() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            
            #line default
            #line hidden
            this.HfldLocationID = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "HfldLocationID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtLocationID() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtLocationID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "TxtLocationID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "TxtName";
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDescription() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDescription = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "TxtDescription";
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtFeetOfRack() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 64 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtFeetOfRack = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 64 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "TxtFeetOfRack";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvFeetOfRack() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvFeetOfRack = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "CompvFeetOfRack";
            
            #line default
            #line hidden
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ControlToValidate = "TxtFeetOfRack";
            
            #line default
            #line hidden
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ErrorMessage = "Invalid integer!";
            
            #line default
            #line hidden
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnAddRecord() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 70 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnAddRecord = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 70 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "BtnAddRecord";
            
            #line default
            #line hidden
            
            #line 70 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Text = "Add Record";
            
            #line default
            #line hidden
            
            #line 70 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnAddRecord_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnUpdateRecord() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnUpdateRecord = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "BtnUpdateRecord";
            
            #line default
            #line hidden
            
            #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Text = "Update Record";
            
            #line default
            #line hidden
            
            #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnUpdateRecord_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control4() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataField = "LocationID";
            
            #line default
            #line hidden
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.HeaderText = "Location ID";
            
            #line default
            #line hidden
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.SortExpression = "LocationID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control5() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 84 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 84 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataField = "Name";
            
            #line default
            #line hidden
            
            #line 84 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.HeaderText = "Name";
            
            #line default
            #line hidden
            
            #line 84 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 84 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.SortExpression = "Name";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control6() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 85 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataField = "Description";
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.HeaderText = "Description";
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.SortExpression = "Description";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control7() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataField = "FeetOfRack";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.HeaderText = "Feet Of Rack";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.SortExpression = "FeetOfRack";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataFormatString = "{0:N0}";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControl__control10() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "IBtnEdit";
            
            #line default
            #line hidden
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ToolTip = "Click to edit";
            
            #line default
            #line hidden
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.OnClientClick = "javascript:return editItem(\'locationID\', this.alt);";
            
            #line default
            #line hidden
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ImageUrl = "~/Images/Edit.gif";
            
            #line default
            #line hidden
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control10);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control10(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.ImageButton dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.ImageButton)(sender));
            
            #line default
            #line hidden
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 90 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            dataBindingExpressionBuilderTarget.AlternateText = global::System.Convert.ToString( Eval("LocationID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control9(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl1;
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl1 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control11(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(30D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control8() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control9), null);
            
            #line default
            #line hidden
            
            #line 87 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            this.@__BuildControl__control11(@__ctrl.ItemStyle);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControl__control14() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "IBtnDelete";
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ToolTip = "Click to delete";
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.OnClientClick = "javascript:return deleteItem(this.name, this.alt);";
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ImageUrl = "~/Images/Delete.png";
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.CommandName = "Delete";
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control14);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control14(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.ImageButton dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.ImageButton)(sender));
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("LocationID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            dataBindingExpressionBuilderTarget.AlternateText = global::System.Convert.ToString( Eval("LocationID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control13(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl1;
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl1 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(30D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control12() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control13), null);
            
            #line default
            #line hidden
            
            #line 95 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            this.@__BuildControl__control15(@__ctrl.ItemStyle);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control3(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl4 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl5;
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl5 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl6;
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl6 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGridView1() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.GridView1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "GridViewCloverField";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "GridView1";
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "LocationID"};
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DataSourceID = "ObjectDataSource1";
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            this.@__BuildControl__control3(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowDataBound);
            
            #line default
            #line hidden
            
            #line 80 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.RowCreated += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowCreated);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl1;
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl1 = this.@__BuildControlGridView1();
            
            #line default
            #line hidden
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            
            #line default
            #line hidden
            this.UpdatePanel1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            
            #line default
            #line hidden
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "UpdatePanel1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control16(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 110 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t        <br />\r\n\t        <img src=\"Images/ActivityIndicator.gif\" alt=\"\" /> Pro" +
                        "cessing your request.  Please wait....\r\n        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdateProgress @__BuildControlUpdateProgress1() {
            global::System.Web.UI.UpdateProgress @__ctrl;
            
            #line 110 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.UpdateProgress();
            
            #line default
            #line hidden
            this.UpdateProgress1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 110 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ProgressTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control16));
            
            #line default
            #line hidden
            
            #line 110 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "UpdateProgress1";
            
            #line default
            #line hidden
            
            #line 110 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.AssociatedUpdatePanelID = "UpdatePanel1";
            
            #line default
            #line hidden
            
            #line 110 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DisplayAfter = 0;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control18() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 122 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 122 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Name = "LocationID";
            
            #line default
            #line hidden
            
            #line 122 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Type = global::System.TypeCode.Int32;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control17(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.Parameter @__ctrl1;
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ObjectDataSource @__BuildControlObjectDataSource1() {
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl;
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ObjectDataSource();
            
            #line default
            #line hidden
            this.ObjectDataSource1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.ID = "ObjectDataSource1";
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.TypeName = "jmann.BusinessObject.Location";
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.SelectMethod = "SelectAll";
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.SortParameterName = "sortExpression";
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.DeleteMethod = "Delete";
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            this.@__BuildControl__control17(@__ctrl.DeleteParameters);
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Deleted += new System.Web.UI.WebControls.ObjectDataSourceStatusEventHandler(this.ObjectDataSource1_Deleted);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptManager @__ctrl1;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl1 = this.@__BuildControlScriptManager1();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(3548, 646, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HiddenField @__ctrl2;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl2 = this.@__BuildControlHfldLocationID();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl3 = this.@__BuildControlTxtLocationID();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Name:</td>\r\n                <" +
                        "td></td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl4 = this.@__BuildControlTxtName();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Description:</td>\r\n          " +
                        "      <td></td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl5 = this.@__BuildControlTxtDescription();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Feet Of Rack:</td>\r\n         " +
                        "       <td></td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl6 = this.@__BuildControlTxtFeetOfRack();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl7;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl7 = this.@__BuildControlCompvFeetOfRack();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td colspan=\"2\"></td>\r\n\t\t        " +
                        "<td colspan=\"2\">\r\n                    <span id=\"spanAddRecord\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl8;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl8 = this.@__BuildControlBtnAddRecord();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\r\n                    <span id=\"spanUpdateRecord\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl9;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl9 = this.@__BuildControlBtnUpdateRecord();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\r\n                    &nbsp;<input id=\"inpCancel\" type=\"button\" value=\"Can" +
                        "cel\" onclick=\"hideValidators()\" />\r\n                </td>\r\n\t        </tr>\r\n     " +
                        "   </table> \r\n    </div>\r\n    <br />\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdatePanel @__ctrl10;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl10 = this.@__BuildControlUpdatePanel1();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdateProgress @__ctrl11;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl11 = this.@__BuildControlUpdateProgress1();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl12;
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl12 = this.@__BuildControlObjectDataSource1();
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(gridviewaddedit_location_aspx @__ctrl) {
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Title = "Location";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__ctrl.Theme = "Theme1";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Location.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.gridviewaddedit_location_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.gridviewaddedit_location_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -188012012;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
