#pragma checksum "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "856B16E0018597AE9131B86015459EE493441506"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jmann {
    
    
    public partial class AddEdit_CreditCardRecord : System.Web.SessionState.IRequiresSessionState {
        
        
        #line 86 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.Label LblTitle;
        
        #line default
        #line hidden
        
        
        #line 92 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtCreditCardRecordID;
        
        #line default
        #line hidden
        
        
        #line 88 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.Panel PnlPrimaryKey;
        
        #line default
        #line hidden
        
        
        #line 100 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        
        #line default
        #line hidden
        
        
        #line 108 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDate;
        
        #line default
        #line hidden
        
        
        #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvDate;
        
        #line default
        #line hidden
        
        
        #line 121 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtAtmCount;
        
        #line default
        #line hidden
        
        
        #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvAtmCount;
        
        #line default
        #line hidden
        
        
        #line 123 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtAtmTotal;
        
        #line default
        #line hidden
        
        
        #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvAtmTotal;
        
        #line default
        #line hidden
        
        
        #line 130 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtVisaCount;
        
        #line default
        #line hidden
        
        
        #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvVisaCount;
        
        #line default
        #line hidden
        
        
        #line 132 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtVisaTotal;
        
        #line default
        #line hidden
        
        
        #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvVisaTotal;
        
        #line default
        #line hidden
        
        
        #line 138 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtMastercardCount;
        
        #line default
        #line hidden
        
        
        #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvMastercardCount;
        
        #line default
        #line hidden
        
        
        #line 140 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtMastercardTotal;
        
        #line default
        #line hidden
        
        
        #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvMastercardTotal;
        
        #line default
        #line hidden
        
        
        #line 146 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDiscoverCount;
        
        #line default
        #line hidden
        
        
        #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvDiscoverCount;
        
        #line default
        #line hidden
        
        
        #line 148 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDiscoverTotal;
        
        #line default
        #line hidden
        
        
        #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvDiscoverTotal;
        
        #line default
        #line hidden
        
        
        #line 161 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.Button BtnAddRecord;
        
        #line default
        #line hidden
        
        
        #line 162 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.Button BtnUpdateRecord;
        
        #line default
        #line hidden
        
        
        #line 168 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
        protected global::System.Web.UI.WebControls.ObjectDataSource OdsLocationDropDownListData;
        
        #line default
        #line hidden
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
    }
}
namespace ASP {
    
    #line 3 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class addedit_creditcardrecord_aspx : global::jmann.AddEdit_CreditCardRecord, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public addedit_creditcardrecord_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/AddEdit_CreditCardRecord.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.addedit_creditcardrecord_aspx.@__initialized == false)) {
                global::ASP.addedit_creditcardrecord_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[6];
                dependencies[0] = "~/AddEdit_CreditCardRecord.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/UC/footer.ascx";
                dependencies[4] = "~/UC/footer.ascx.cs";
                dependencies[5] = "~/AddEdit_CreditCardRecord.aspx.cs";
                global::ASP.addedit_creditcardrecord_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.addedit_creditcardrecord_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(5650, 4098, true));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLblTitle() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 86 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.LblTitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 86 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "LblTitle";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Text = "Add New CreditCardRecord";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtCreditCardRecordID() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 92 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtCreditCardRecordID = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 92 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtCreditCardRecordID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlPnlPrimaryKey() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 88 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.PnlPrimaryKey = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 88 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "PnlPrimaryKey";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 88 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t        <tr style=\"display: none\">\r\n\t\t        <td>Credit Card Record ID:</td>\r" +
                        "\n                <td></td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 88 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl1 = this.@__BuildControlTxtCreditCardRecordID();
            
            #line default
            #line hidden
            
            #line 88 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 88 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n                <td colspan=\"2\"></td>\r\n\t        </tr>\r\n\t        "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlLocation() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 100 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.ddlLocation = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 100 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "ddlLocation";
            
            #line default
            #line hidden
            
            #line 100 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 100 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlLocation_SelectedIndexChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDate() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 108 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "TextBoxDate";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 108 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtDate";
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.txtDate_Changed);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvDate() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvDate = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvDate";
            
            #line default
            #line hidden
            
            #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtDate";
            
            #line default
            #line hidden
            
            #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid date!";
            
            #line default
            #line hidden
            
            #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 109 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Date;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtAtmCount() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 121 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtAtmCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 121 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtAtmCount";
            
            #line default
            #line hidden
            
            #line 121 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvAtmCount() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvAtmCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvAtmCount";
            
            #line default
            #line hidden
            
            #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtAtmCount";
            
            #line default
            #line hidden
            
            #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid integer!";
            
            #line default
            #line hidden
            
            #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 122 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtAtmTotal() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 123 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtAtmTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 123 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtAtmTotal";
            
            #line default
            #line hidden
            
            #line 123 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvAtmTotal() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvAtmTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvAtmTotal";
            
            #line default
            #line hidden
            
            #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtAtmTotal";
            
            #line default
            #line hidden
            
            #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid currency!";
            
            #line default
            #line hidden
            
            #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 124 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Currency;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtVisaCount() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 130 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtVisaCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 130 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtVisaCount";
            
            #line default
            #line hidden
            
            #line 130 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvVisaCount() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvVisaCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvVisaCount";
            
            #line default
            #line hidden
            
            #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtVisaCount";
            
            #line default
            #line hidden
            
            #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid integer!";
            
            #line default
            #line hidden
            
            #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 131 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtVisaTotal() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 132 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtVisaTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 132 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtVisaTotal";
            
            #line default
            #line hidden
            
            #line 132 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvVisaTotal() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvVisaTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvVisaTotal";
            
            #line default
            #line hidden
            
            #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtVisaTotal";
            
            #line default
            #line hidden
            
            #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid currency!";
            
            #line default
            #line hidden
            
            #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 133 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Currency;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtMastercardCount() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 138 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtMastercardCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 138 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtMastercardCount";
            
            #line default
            #line hidden
            
            #line 138 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvMastercardCount() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvMastercardCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvMastercardCount";
            
            #line default
            #line hidden
            
            #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtMastercardCount";
            
            #line default
            #line hidden
            
            #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid integer!";
            
            #line default
            #line hidden
            
            #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 139 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtMastercardTotal() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 140 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtMastercardTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 140 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtMastercardTotal";
            
            #line default
            #line hidden
            
            #line 140 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvMastercardTotal() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvMastercardTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvMastercardTotal";
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtMastercardTotal";
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid currency!";
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Currency;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDiscoverCount() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 146 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDiscoverCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 146 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtDiscoverCount";
            
            #line default
            #line hidden
            
            #line 146 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvDiscoverCount() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvDiscoverCount = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvDiscoverCount";
            
            #line default
            #line hidden
            
            #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtDiscoverCount";
            
            #line default
            #line hidden
            
            #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid integer!";
            
            #line default
            #line hidden
            
            #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 147 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDiscoverTotal() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 148 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDiscoverTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 148 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "TxtDiscoverTotal";
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "text-align: right;");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvDiscoverTotal() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvDiscoverTotal = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "CompvDiscoverTotal";
            
            #line default
            #line hidden
            
            #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ControlToValidate = "TxtDiscoverTotal";
            
            #line default
            #line hidden
            
            #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ErrorMessage = "Invalid currency!";
            
            #line default
            #line hidden
            
            #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 149 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Currency;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnAddRecord() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 161 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnAddRecord = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 161 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "BtnAddRecord";
            
            #line default
            #line hidden
            
            #line 161 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Text = "Add Record";
            
            #line default
            #line hidden
            
            #line 161 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnAddRecord_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnUpdateRecord() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 162 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnUpdateRecord = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 162 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "BtnUpdateRecord";
            
            #line default
            #line hidden
            
            #line 162 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Text = "Update Record";
            
            #line default
            #line hidden
            
            #line 162 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 162 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnUpdateRecord_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ObjectDataSource @__BuildControlOdsLocationDropDownListData() {
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl;
            
            #line 168 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ObjectDataSource();
            
            #line default
            #line hidden
            this.OdsLocationDropDownListData = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 168 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.ID = "OdsLocationDropDownListData";
            
            #line default
            #line hidden
            
            #line 168 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.SelectMethod = "SelectLocationDropDownListData";
            
            #line default
            #line hidden
            
            #line 168 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.TypeName = "jmann.BusinessObject.Location";
            
            #line default
            #line hidden
            
            #line 168 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.OldValuesParameterFormatString = "original_{0}";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        <h3 id=\"h3AddEditRecord\" class=\"ui-widget-header\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl1 = this.@__BuildControlLblTitle();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</h3>\r\n        <table>\r\n\t        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl2 = this.@__BuildControlPnlPrimaryKey();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <tr>\r\n                <td>Location</td>\r\n                <td></td>\r" +
                        "\n  \t\t        <td>\r\n                   "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl3 = this.@__BuildControlddlLocation();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n\t\t        <td>Date:" +
                        "</td>\r\n                <td></td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl4 = this.@__BuildControlTxtDate();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl5;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl5 = this.@__BuildControlCompvDate();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(9748, 301, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl6 = this.@__BuildControlTxtAtmCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl7;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl7 = this.@__BuildControlCompvAtmCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n                <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl8 = this.@__BuildControlTxtAtmTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl9;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl9 = this.@__BuildControlCompvAtmTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Visa:</td>\r\n               " +
                        " <td></td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl10 = this.@__BuildControlTxtVisaCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl11;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl11 = this.@__BuildControlCompvVisaCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl12 = this.@__BuildControlTxtVisaTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl13;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl13 = this.@__BuildControlCompvVisaTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Mastercard Count:</td>\r\n     " +
                        "           <td></td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl14 = this.@__BuildControlTxtMastercardCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl15;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl15 = this.@__BuildControlCompvMastercardCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl16;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl16 = this.@__BuildControlTxtMastercardTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl17;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl17 = this.@__BuildControlCompvMastercardTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Discover Count:</td>\r\n       " +
                        "         <td></td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl18;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl18 = this.@__BuildControlTxtDiscoverCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl19;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl19 = this.@__BuildControlCompvDiscoverCount();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl20;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl20 = this.@__BuildControlTxtDiscoverTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl21;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl21 = this.@__BuildControlCompvDiscoverTotal();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(10049, 463, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl22;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl22 = this.@__BuildControlBtnAddRecord();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl23;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl23 = this.@__BuildControlBtnUpdateRecord();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl23);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    &nbsp;<input id=\"inpCancel\" type=\"button\" value=\"Cancel\" on" +
                        "click=\"window.location = \'GridView_CreditCardRecord.aspx\'; return false;\" />\r\n  " +
                        "              </td>\r\n\t        </tr>\r\n        </table> \r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl24;
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl24 = this.@__BuildControlOdsLocationDropDownListData();
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(@__ctrl24);
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(addedit_creditcardrecord_aspx @__ctrl) {
            
            #line 1 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Title = "CreditCardRecord";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__ctrl.Theme = "Theme1";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 85 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\JMann\Finance\Application\Finance\AddEdit_CreditCardRecord.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.addedit_creditcardrecord_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.addedit_creditcardrecord_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -785402208;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
