#pragma checksum "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A43E2404F6545BEF1416C6902CDC419E9C726683"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jmann {
    
    
    public partial class GridView_Carts : System.Web.SessionState.IRequiresSessionState {
        
        
        #line 13 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        #line default
        #line hidden
        
        
        #line 15 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        
        #line default
        #line hidden
        
        
        #line 23 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.WebControls.HyperLink hlAddNewRecord;
        
        #line default
        #line hidden
        
        
        #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        #line default
        #line hidden
        
        
        #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        #line default
        #line hidden
        
        
        #line 66 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        
        #line default
        #line hidden
        
        
        #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
        
        #line default
        #line hidden
        
        
        #line 86 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
        protected global::System.Web.UI.WebControls.ObjectDataSource OdsLocationDropDownListData;
        
        #line default
        #line hidden
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
    }
}
namespace ASP {
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class gridview_carts_aspx : global::jmann.GridView_Carts, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public gridview_carts_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/GridView_Carts.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.gridview_carts_aspx.@__initialized == false)) {
                global::ASP.gridview_carts_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[6];
                dependencies[0] = "~/GridView_Carts.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/UC/footer.ascx";
                dependencies[4] = "~/UC/footer.ascx.cs";
                dependencies[5] = "~/GridView_Carts.aspx.cs";
                global::ASP.gridview_carts_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.gridview_carts_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <script src=\"Scripts/gridview-script.js\" type=\"text/javascript\"></script>\r\n" +
                        "    <script type=\"text/javascript\">\r\n        $(function () {\r\n            Initia" +
                        "lizeDeleteConfirmation();\r\n        });\r\n    </script>\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptManager @__BuildControlScriptManager1() {
            global::System.Web.UI.ScriptManager @__ctrl;
            
            #line 13 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.ScriptManager();
            
            #line default
            #line hidden
            this.ScriptManager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 13 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "ScriptManager1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlLocation() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 15 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.ddlLocation = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 15 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "ddlLocation";
            
            #line default
            #line hidden
            
            #line 15 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 15 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlLocation_SelectedIndexChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlhlAddNewRecord() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 23 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.hlAddNewRecord = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 23 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "hlAddNewRecord";
            
            #line default
            #line hidden
            
            #line 23 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Text = "Add New Record";
            
            #line default
            #line hidden
            
            #line 23 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.NavigateUrl = "~/AddEdit_Carts.aspx?operation=add";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control6() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 34 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(2, 1);
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                            <a href=\"AddEdit_Carts.aspx?operation=update&cartsi" +
                    "d=");
            @__ctrl.SetStaticString(1, "\" title=\"Click to edit\"><img src=\"Images/Edit.gif\" alt=\"\" style=\"border: none;\" /" +
                    "></a>\r\n                        ");
            
            #line 34 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control6);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__control6(object sender, System.EventArgs e) {
            System.Web.UI.IDataItemContainer Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 34 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 34 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 34 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("CartsID"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control5(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control7(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(30D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control4() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control5), null);
            
            #line default
            #line hidden
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.@__BuildControl__control7(@__ctrl.ItemStyle);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControl__control10() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "IBtnDelete";
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ToolTip = "Click to delete";
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.OnClientClick = "javascript:return deleteItem(this.name, this.alt);";
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ImageUrl = "~/Images/Delete.png";
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.CommandName = "Delete";
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control10);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control10(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.ImageButton dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.ImageButton)(sender));
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("CartsID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 40 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            dataBindingExpressionBuilderTarget.AlternateText = global::System.Convert.ToString( Eval("CartsID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control9(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl1;
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl1 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control11(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(30D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control8() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control9), null);
            
            #line default
            #line hidden
            
            #line 37 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.@__BuildControl__control11(@__ctrl.ItemStyle);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control12() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 47 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 47 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "CartsID";
            
            #line default
            #line hidden
            
            #line 47 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Carts ID";
            
            #line default
            #line hidden
            
            #line 47 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 47 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "CartsID";
            
            #line default
            #line hidden
            
            #line 47 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "Date";
            
            #line default
            #line hidden
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Date";
            
            #line default
            #line hidden
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "Date";
            
            #line default
            #line hidden
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:yyyy/MM/dd}";
            
            #line default
            #line hidden
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 48 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLinkField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.HyperLinkField @__ctrl;
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLinkField();
            
            #line default
            #line hidden
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataTextField = "LocationID";
            
            #line default
            #line hidden
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Location ID";
            
            #line default
            #line hidden
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataNavigateUrlFields = new string[] {
                    "LocationID"};
            
            #line default
            #line hidden
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataNavigateUrlFormatString = "~/Detail_Location.aspx?locationid={0}";
            
            #line default
            #line hidden
            
            #line 49 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "LocationID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control15() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "CartsWorkedHard";
            
            #line default
            #line hidden
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Carts Worked Hard";
            
            #line default
            #line hidden
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "CartsWorkedHard";
            
            #line default
            #line hidden
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:F2}";
            
            #line default
            #line hidden
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 50 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control16() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "CartsWorkedSoft";
            
            #line default
            #line hidden
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Carts Worked Soft";
            
            #line default
            #line hidden
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "CartsWorkedSoft";
            
            #line default
            #line hidden
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:F2}";
            
            #line default
            #line hidden
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 51 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control17() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "CartsWorkedTotal";
            
            #line default
            #line hidden
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Carts Worked Total";
            
            #line default
            #line hidden
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "CartsWorkedTotal";
            
            #line default
            #line hidden
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:F2}";
            
            #line default
            #line hidden
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 52 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control18() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "OnHandHard";
            
            #line default
            #line hidden
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "On Hand Hard";
            
            #line default
            #line hidden
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "OnHandHard";
            
            #line default
            #line hidden
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:F2}";
            
            #line default
            #line hidden
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 53 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control19() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "OnHandSoft";
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "On Hand Soft";
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "OnHandSoft";
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:F2}";
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 54 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control20() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "OnHandTotal";
            
            #line default
            #line hidden
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "On Hand Total";
            
            #line default
            #line hidden
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "OnHandTotal";
            
            #line default
            #line hidden
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:F2}";
            
            #line default
            #line hidden
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 55 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control21() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "HangTotal";
            
            #line default
            #line hidden
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Hang Total";
            
            #line default
            #line hidden
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "HangTotal";
            
            #line default
            #line hidden
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:N0}";
            
            #line default
            #line hidden
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 56 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control22() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "ThrownCount";
            
            #line default
            #line hidden
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Thrown Count";
            
            #line default
            #line hidden
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "ThrownCount";
            
            #line default
            #line hidden
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:N0}";
            
            #line default
            #line hidden
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 57 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control23() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "ThrownLbs";
            
            #line default
            #line hidden
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Thrown Lbs";
            
            #line default
            #line hidden
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "ThrownLbs";
            
            #line default
            #line hidden
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:N0}";
            
            #line default
            #line hidden
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 58 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control24() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataField = "RaggedLbs";
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HeaderText = "Ragged Lbs";
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortExpression = "RaggedLbs";
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataFormatString = "{0:N0}";
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control3(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.TemplateField @__ctrl1;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl2;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl2 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl3 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl4 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLinkField @__ctrl5;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl5 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl6 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl7;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl7 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl8;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl8 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl9;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl9 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl10;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl10 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl11;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl11 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl12;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl12 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl13;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl13 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl14;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl14 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl15;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl15 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl15);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGridView1() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.GridView1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "GridViewCloverField";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "GridView1";
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "CartsID"};
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DataSourceID = "ObjectDataSource1";
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.@__BuildControl__control3(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowDataBound);
            
            #line default
            #line hidden
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.RowCreated += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowCreated);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl1;
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl1 = this.@__BuildControlGridView1();
            
            #line default
            #line hidden
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            
            #line default
            #line hidden
            this.UpdatePanel1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            
            #line default
            #line hidden
            
            #line 26 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "UpdatePanel1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control25(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t        <br />\r\n\t        <img src=\"Images/ActivityIndicator.gif\" alt=\"\" /> Pro" +
                        "cessing your request.  Please wait....\r\n        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdateProgress @__BuildControlUpdateProgress1() {
            global::System.Web.UI.UpdateProgress @__ctrl;
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.UpdateProgress();
            
            #line default
            #line hidden
            this.UpdateProgress1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ProgressTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control25));
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "UpdateProgress1";
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.AssociatedUpdatePanelID = "UpdatePanel1";
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DisplayAfter = 0;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control27() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Name = "sortExpression";
            
            #line default
            #line hidden
            
            #line 78 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Type = global::System.TypeCode.String;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ControlParameter @__BuildControl__control28() {
            global::System.Web.UI.WebControls.ControlParameter @__ctrl;
            
            #line 79 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ControlParameter();
            
            #line default
            #line hidden
            
            #line 79 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ControlID = "DdlLocation";
            
            #line default
            #line hidden
            
            #line 79 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Type = global::System.TypeCode.Int32;
            
            #line default
            #line hidden
            
            #line 79 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.PropertyName = "SelectedValue";
            
            #line default
            #line hidden
            
            #line 79 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Name = "LocationID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control26(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.Parameter @__ctrl1;
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl1 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ControlParameter @__ctrl2;
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl2 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control30() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 82 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 82 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Name = "CartsID";
            
            #line default
            #line hidden
            
            #line 82 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Type = global::System.TypeCode.Int32;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control29(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.Parameter @__ctrl1;
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl1 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ObjectDataSource @__BuildControlObjectDataSource1() {
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl;
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ObjectDataSource();
            
            #line default
            #line hidden
            this.ObjectDataSource1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "ObjectDataSource1";
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.TypeName = "jmann.BusinessObject.Carts";
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SelectMethod = "SelectCartsCollectionByLocation";
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SortParameterName = "sortExpression";
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.DeleteMethod = "Delete";
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.@__BuildControl__control26(@__ctrl.SelectParameters);
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.@__BuildControl__control29(@__ctrl.DeleteParameters);
            
            #line default
            #line hidden
            
            #line 73 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Deleted += new System.Web.UI.WebControls.ObjectDataSourceStatusEventHandler(this.ObjectDataSource1_Deleted);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ObjectDataSource @__BuildControlOdsLocationDropDownListData() {
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl;
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ObjectDataSource();
            
            #line default
            #line hidden
            this.OdsLocationDropDownListData = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.ID = "OdsLocationDropDownListData";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.SelectMethod = "SelectLocationDropDownListData";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.TypeName = "jmann.BusinessObject.Location";
            
            #line default
            #line hidden
            
            #line 86 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.OldValuesParameterFormatString = "original_{0}";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptManager @__ctrl1;
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl1 = this.@__BuildControlScriptManager1();
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <b>LocationID:</b>\r\n       "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl2 = this.@__BuildControlddlLocation();
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(22333, 295, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl3;
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl3 = this.@__BuildControlhlAddNewRecord();
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <br /><br />\r\n-->\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdatePanel @__ctrl4;
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl4 = this.@__BuildControlUpdatePanel1();
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdateProgress @__ctrl5;
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl5 = this.@__BuildControlUpdateProgress1();
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl6;
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl6 = this.@__BuildControlObjectDataSource1();
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl7;
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl7 = this.@__BuildControlOdsLocationDropDownListData();
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(gridview_carts_aspx @__ctrl) {
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Title = "Carts";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__ctrl.Theme = "Theme1";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 12 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\JMann\Finance\Application\Finance\GridView_Carts.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.gridview_carts_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.gridview_carts_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1804135393;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
