#pragma checksum "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "DDC9D09EB57AA3E17035E715B209B44731DD3462"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jmann {
    
    
    public partial class GridViewAddEdit_Employee : System.Web.SessionState.IRequiresSessionState {
        
        
        #line 42 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        #line default
        #line hidden
        
        
        #line 45 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        
        #line default
        #line hidden
        
        
        #line 59 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.HiddenField HfldEmployeeID;
        
        #line default
        #line hidden
        
        
        #line 60 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtEmployeeID;
        
        #line default
        #line hidden
        
        
        #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtDepartment;
        
        #line default
        #line hidden
        
        
        #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvDepartment;
        
        #line default
        #line hidden
        
        
        #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtName;
        
        #line default
        #line hidden
        
        
        #line 76 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtLocationID;
        
        #line default
        #line hidden
        
        
        #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.CompareValidator CompvLocationID;
        
        #line default
        #line hidden
        
        
        #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtLastName;
        
        #line default
        #line hidden
        
        
        #line 88 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.TextBox TxtFirstName;
        
        #line default
        #line hidden
        
        
        #line 93 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.CheckBox CbxExpired;
        
        #line default
        #line hidden
        
        
        #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.Button BtnAddRecord;
        
        #line default
        #line hidden
        
        
        #line 99 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.Button BtnUpdateRecord;
        
        #line default
        #line hidden
        
        
        #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        #line default
        #line hidden
        
        
        #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        #line default
        #line hidden
        
        
        #line 141 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.UpdateProgress UpdateProgress1;
        
        #line default
        #line hidden
        
        
        #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
        
        #line default
        #line hidden
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
    }
}
namespace ASP {
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class gridviewaddedit_employee_aspx : global::jmann.GridViewAddEdit_Employee, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public gridviewaddedit_employee_aspx() {
            string[] dependencies;
            
            #line 912304 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/GridViewAddEdit_Employee.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.gridviewaddedit_employee_aspx.@__initialized == false)) {
                global::ASP.gridviewaddedit_employee_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[6];
                dependencies[0] = "~/GridViewAddEdit_Employee.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/UC/footer.ascx";
                dependencies[4] = "~/UC/footer.ascx.cs";
                dependencies[5] = "~/GridViewAddEdit_Employee.aspx.cs";
                global::ASP.gridviewaddedit_employee_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.gridviewaddedit_employee_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent1));
        }
        
        private void @__RenderContent1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.WriteUTF8ResourceString(@__w, 21141, 529, true);
            
            #line 17 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
     @__w.Write(TxtEmployeeID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").attr(\'disabled\', false);\r\n            $(\"#");
            
            #line 18 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtEmployeeID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 19 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtDepartment.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 20 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 21 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtLocationID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 22 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtLastName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 23 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtFirstName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n            $(\"#");
            
            #line 24 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(CbxExpired.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(\'\');\r\n        }\r\n\r\n        function assignRetrievedItems(msg) {\r\n\t        " +
                    "$(\"#");
            
            #line 28 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
     @__w.Write(HfldEmployeeID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(msg.d.EmployeeID);\r\n\t        $(\"#");
            
            #line 29 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
     @__w.Write(TxtEmployeeID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").attr(\'disabled\', true);\r\n            $(\"#");
            
            #line 30 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtEmployeeID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.EmployeeID));\r\n            $(\"#");
            
            #line 31 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtDepartment.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.Department));\r\n            $(\"#");
            
            #line 32 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.Name));\r\n            $(\"#");
            
            #line 33 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtLocationID.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.LocationID));\r\n            $(\"#");
            
            #line 34 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtLastName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.LastName));\r\n            $(\"#");
            
            #line 35 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(TxtFirstName.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.FirstName));\r\n            $(\"#");
            
            #line 36 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
        @__w.Write(CbxExpired.ClientID );

            
            #line default
            #line hidden
            @__w.Write("\").val(ConvertNullToString(msg.d.Expired));\r\n        }\r\n    </script>\r\n");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.ScriptManager @__BuildControlScriptManager1() {
            global::System.Web.UI.ScriptManager @__ctrl;
            
            #line 42 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.ScriptManager();
            
            #line default
            #line hidden
            this.ScriptManager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 42 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "ScriptManager1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlLocation() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 45 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.ddlLocation = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 45 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "ddlLocation";
            
            #line default
            #line hidden
            
            #line 45 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 45 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.ddlLocation_SelectedIndexChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHfldEmployeeID() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            
            #line default
            #line hidden
            this.HfldEmployeeID = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 59 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "HfldEmployeeID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtEmployeeID() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 60 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtEmployeeID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 60 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "TxtEmployeeID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtDepartment() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtDepartment = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 65 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "TxtDepartment";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvDepartment() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvDepartment = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "CompvDepartment";
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ControlToValidate = "TxtDepartment";
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ErrorMessage = "Invalid integer!";
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 66 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "TxtName";
            
            #line default
            #line hidden
            
            #line 71 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtLocationID() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 76 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtLocationID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 76 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "TxtLocationID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CompareValidator @__BuildControlCompvLocationID() {
            global::System.Web.UI.WebControls.CompareValidator @__ctrl;
            
            #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CompareValidator();
            
            #line default
            #line hidden
            this.CompvLocationID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "CompvLocationID";
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ControlToValidate = "TxtLocationID";
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ErrorMessage = "Invalid integer!";
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Operator = global::System.Web.UI.WebControls.ValidationCompareOperator.DataTypeCheck;
            
            #line default
            #line hidden
            
            #line 77 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Type = global::System.Web.UI.WebControls.ValidationDataType.Integer;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtLastName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtLastName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "TxtLastName";
            
            #line default
            #line hidden
            
            #line 83 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTxtFirstName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 88 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TxtFirstName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 88 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "TxtFirstName";
            
            #line default
            #line hidden
            
            #line 88 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlCbxExpired() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 93 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.CbxExpired = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 93 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "CbxExpired";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnAddRecord() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnAddRecord = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "BtnAddRecord";
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Text = "Add Record";
            
            #line default
            #line hidden
            
            #line 98 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnAddRecord_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlBtnUpdateRecord() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 99 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.BtnUpdateRecord = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 99 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "BtnUpdateRecord";
            
            #line default
            #line hidden
            
            #line 99 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Text = "Update Record";
            
            #line default
            #line hidden
            
            #line 99 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Click += new System.EventHandler(this.BtnUpdateRecord_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control4() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 111 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 111 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataField = "EmployeeID";
            
            #line default
            #line hidden
            
            #line 111 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HeaderText = "Employee ID";
            
            #line default
            #line hidden
            
            #line 111 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 111 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SortExpression = "EmployeeID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control5() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataField = "Department";
            
            #line default
            #line hidden
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HeaderText = "Department";
            
            #line default
            #line hidden
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SortExpression = "Department";
            
            #line default
            #line hidden
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataFormatString = "{0:N0}";
            
            #line default
            #line hidden
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 112 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control6() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 113 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 113 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataField = "Name";
            
            #line default
            #line hidden
            
            #line 113 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HeaderText = "Name";
            
            #line default
            #line hidden
            
            #line 113 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 113 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SortExpression = "Name";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control7() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataField = "LocationID";
            
            #line default
            #line hidden
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HeaderText = "Location ID";
            
            #line default
            #line hidden
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SortExpression = "LocationID";
            
            #line default
            #line hidden
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataFormatString = "{0:N0}";
            
            #line default
            #line hidden
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HtmlEncode = false;
            
            #line default
            #line hidden
            
            #line 114 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Right;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control8() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 115 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 115 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataField = "LastName";
            
            #line default
            #line hidden
            
            #line 115 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HeaderText = "Last Name";
            
            #line default
            #line hidden
            
            #line 115 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 115 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SortExpression = "LastName";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control9() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 116 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 116 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataField = "FirstName";
            
            #line default
            #line hidden
            
            #line 116 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HeaderText = "First Name";
            
            #line default
            #line hidden
            
            #line 116 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 116 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SortExpression = "FirstName";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBoxField @__BuildControl__control10() {
            global::System.Web.UI.WebControls.CheckBoxField @__ctrl;
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBoxField();
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataField = "Expired";
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HeaderText = "Expired";
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ReadOnly = true;
            
            #line default
            #line hidden
            
            #line 117 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SortExpression = "Expired";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControl__control13() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "IBtnEdit";
            
            #line default
            #line hidden
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ToolTip = "Click to edit";
            
            #line default
            #line hidden
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.OnClientClick = "javascript:return editItem(\'employeeID\', this.alt);";
            
            #line default
            #line hidden
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ImageUrl = "~/Images/Edit.gif";
            
            #line default
            #line hidden
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control13);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control13(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.ImageButton dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.ImageButton)(sender));
            
            #line default
            #line hidden
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 121 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            dataBindingExpressionBuilderTarget.AlternateText = global::System.Convert.ToString( Eval("EmployeeID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control12(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl1;
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control14(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(30D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control11() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control12), null);
            
            #line default
            #line hidden
            
            #line 118 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.@__BuildControl__control14(@__ctrl.ItemStyle);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControl__control17() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "IBtnDelete";
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ToolTip = "Click to delete";
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.OnClientClick = "javascript:return deleteItem(this.name, this.alt);";
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ImageUrl = "~/Images/Delete.png";
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.CommandName = "Delete";
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control17);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control17(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.ImageButton dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.ImageButton)(sender));
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("EmployeeID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 129 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            dataBindingExpressionBuilderTarget.AlternateText = global::System.Convert.ToString( Eval("EmployeeID") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control16(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl1;
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control18(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(30D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control15() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control16), null);
            
            #line default
            #line hidden
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 126 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.@__BuildControl__control18(@__ctrl.ItemStyle);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control3(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl4 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl5;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl5 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl6 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBoxField @__ctrl7;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl7 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl8;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl8 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl9;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl9 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl9);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGridView1() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.GridView1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "GridViewCloverField";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "GridView1";
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "EmployeeID"};
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DataSourceID = "ObjectDataSource1";
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.@__BuildControl__control3(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowDataBound);
            
            #line default
            #line hidden
            
            #line 108 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.RowCreated += new System.Web.UI.WebControls.GridViewRowEventHandler(this.GridView1_RowCreated);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl1;
            
            #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl1 = this.@__BuildControlGridView1();
            
            #line default
            #line hidden
            
            #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel1() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            
            #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            
            #line default
            #line hidden
            this.UpdatePanel1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            
            #line default
            #line hidden
            
            #line 106 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "UpdatePanel1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control19(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 141 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t        <br />\r\n\t        <img src=\"Images/ActivityIndicator.gif\" alt=\"\" /> Pro" +
                        "cessing your request.  Please wait....\r\n        "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdateProgress @__BuildControlUpdateProgress1() {
            global::System.Web.UI.UpdateProgress @__ctrl;
            
            #line 141 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.UpdateProgress();
            
            #line default
            #line hidden
            this.UpdateProgress1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 141 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ProgressTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control19));
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "UpdateProgress1";
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.AssociatedUpdatePanelID = "UpdatePanel1";
            
            #line default
            #line hidden
            
            #line 141 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DisplayAfter = 0;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ControlParameter @__BuildControl__control21() {
            global::System.Web.UI.WebControls.ControlParameter @__ctrl;
            
            #line 153 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ControlParameter();
            
            #line default
            #line hidden
            
            #line 153 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ControlID = "ddlLocation";
            
            #line default
            #line hidden
            
            #line 153 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Type = global::System.TypeCode.Int32;
            
            #line default
            #line hidden
            
            #line 153 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.PropertyName = "SelectedValue";
            
            #line default
            #line hidden
            
            #line 153 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Name = "locationID";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control20(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.ControlParameter @__ctrl1;
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control23() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 156 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 156 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Name = "EmployeeID";
            
            #line default
            #line hidden
            
            #line 156 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Type = global::System.TypeCode.Int32;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control22(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.Parameter @__ctrl1;
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl1 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ObjectDataSource @__BuildControlObjectDataSource1() {
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl;
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ObjectDataSource();
            
            #line default
            #line hidden
            this.ObjectDataSource1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.ID = "ObjectDataSource1";
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.TypeName = "jmann.BusinessObject.Employee";
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.SelectMethod = "SelectEmployeeCollectionByLocation";
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.DeleteMethod = "Delete";
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.@__BuildControl__control20(@__ctrl.SelectParameters);
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.@__BuildControl__control22(@__ctrl.DeleteParameters);
            
            #line default
            #line hidden
            
            #line 148 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Deleted += new System.Web.UI.WebControls.ObjectDataSourceStatusEventHandler(this.ObjectDataSource1_Deleted);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.ScriptManager @__ctrl1;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl1 = this.@__BuildControlScriptManager1();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div>\r\n    <b>LocationID:</b>\r\n       "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl2 = this.@__BuildControlddlLocation();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(21670, 663, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HiddenField @__ctrl3;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl3 = this.@__BuildControlHfldEmployeeID();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl4 = this.@__BuildControlTxtEmployeeID();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Department:</td>\r\n           " +
                        "     <td></td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl5 = this.@__BuildControlTxtDepartment();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl6;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl6 = this.@__BuildControlCompvDepartment();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Name:</td>\r\n                <" +
                        "td></td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl7 = this.@__BuildControlTxtName();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n<!--        <tr>\r\n\t\t        <td>Location ID:</td>\r\n       " +
                        "         <td></td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl8 = this.@__BuildControlTxtLocationID();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t\t        <td>"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CompareValidator @__ctrl9;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl9 = this.@__BuildControlCompvLocationID();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n-->\t\r\n\t        <tr>\r\n\t\t        <td>Last Name:</td>\r\n      " +
                        "          <td></td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl10 = this.@__BuildControlTxtLastName();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>First Name:</td>\r\n           " +
                        "     <td></td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl11;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl11 = this.@__BuildControlTxtFirstName();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td>Expired:</td>\r\n              " +
                        "  <td></td>\r\n\t\t        <td colspan=\"2\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl12;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl12 = this.@__BuildControlCbxExpired();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n\t        </tr>\r\n\t        <tr>\r\n\t\t        <td colspan=\"2\"></td>\r\n\t\t        " +
                        "<td colspan=\"2\">\r\n                    <span id=\"spanAddRecord\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl13;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl13 = this.@__BuildControlBtnAddRecord();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\r\n                    <span id=\"spanUpdateRecord\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl14;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl14 = this.@__BuildControlBtnUpdateRecord();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\r\n                    &nbsp;<input id=\"inpCancel\" type=\"button\" value=\"Can" +
                        "cel\" onclick=\"hideValidators()\" />\r\n                </td>\r\n\t        </tr>\r\n     " +
                        "   </table> \r\n    </div>\r\n    <br />\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdatePanel @__ctrl15;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl15 = this.@__BuildControlUpdatePanel1();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.UpdateProgress @__ctrl16;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl16 = this.@__BuildControlUpdateProgress1();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl17;
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl17 = this.@__BuildControlObjectDataSource1();
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(gridviewaddedit_employee_aspx @__ctrl) {
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Title = "Employee";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__ctrl.Theme = "Theme1";
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 41 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "D:\JMann\Finance\Application\Finance\GridViewAddEdit_Employee.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.gridviewaddedit_employee_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.gridviewaddedit_employee_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1479123558;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
